### ISSUE TITLE
Vaadin 14.0.0.beta2 Full Stack App starter does not compile

### ISSUE THREAD

**Issue by johannesh2** [vaadin/full-stack-starter#26]
Mvn install fails when running `mvn install`

```
ERROR in ../target/frontend/generated-flow-imports.js?babel-target=es5
Module not found: Error: Can't resolve 'src/components/amount-field.js?babel-target=es5' in 'C:\Users\Johannes\Downloads\npmbakery\target\frontend'
 @ ../target/frontend/generated-flow-imports.js?babel-target=es5 13:0-40

ERROR in ../target/frontend/generated-flow-imports.js?babel-target=es6
Module not found: Error: Can't resolve 'src/components/amount-field.js?babel-target=es6' in 'C:\Users\Johannes\Downloads\npmbakery\target\frontend'
 @ ../target/frontend/generated-flow-imports.js?babel-target=es6 13:0-40

ERROR in ../target/frontend/generated-flow-imports.js?babel-target=es5
Module not found: Error: Can't resolve 'src/components/search-bar.js?babel-target=es5' in 'C:\Users\Johannes\Downloads\npmbakery\target\frontend'
 @ ../target/frontend/generated-flow-imports.js?babel-target=es5 12:0-38

ERROR in ../target/frontend/generated-flow-imports.js?babel-target=es6
Module not found: Error: Can't resolve 'src/components/search-bar.js?babel-target=es6' in 'C:\Users\Johannes\Downloads\npmbakery\target\frontend'
 @ ../target/frontend/generated-flow-imports.js?babel-target=es6 12:0-38

ERROR in ../target/frontend/generated-flow-imports.js?babel-target=es5
Module not found: Error: Can't resolve 'src/views/dashboard/dashboard-counter-label.js?babel-target=es5' in 'C:\Users\Johannes\Downloads\npmbakery\target\frontend'
 @ ../target/frontend/generated-flow-imports.js?babel-target=es5 11:0-56

ERROR in ../target/frontend/generated-flow-imports.js?babel-target=es6
Module not found: Error: Can't resolve 'src/views/dashboard/dashboard-counter-label.js?babel-target=es6' in 'C:\Users\Johannes\Downloads\npmbakery\target\frontend'
 @ ../target/frontend/generated-flow-imports.js?babel-target=es6 11:0-56

ERROR in ../target/frontend/generated-flow-imports.js?babel-target=es5
Module not found: Error: Can't resolve 'src/views/dashboard/dashboard-view.js?babel-target=es5' in 'C:\Users\Johannes\Downloads\npmbakery\target\frontend'
 @ ../target/frontend/generated-flow-imports.js?babel-target=es5 10:0-47

ERROR in ../target/frontend/generated-flow-imports.js?babel-target=es6
Module not found: Error: Can't resolve 'src/views/dashboard/dashboard-view.js?babel-target=es6' in 'C:\Users\Johannes\Downloads\npmbakery\target\frontend'
 @ ../target/frontend/generated-flow-imports.js?babel-target=es6 10:0-47

ERROR in ../target/frontend/generated-flow-imports.js?babel-target=es5
Module not found: Error: Can't resolve 'src/views/errors/access-denied-view.js?babel-target=es5' in 'C:\Users\Johannes\Downloads\npmbakery\target\frontend'
 @ ../target/frontend/generated-flow-imports.js?babel-target=es5 9:0-48

ERROR in ../target/frontend/generated-flow-imports.js?babel-target=es6
Module not found: Error: Can't resolve 'src/views/errors/access-denied-view.js?babel-target=es6' in 'C:\Users\Johannes\Downloads\npmbakery\target\frontend'
 @ ../target/frontend/generated-flow-imports.js?babel-target=es6 9:0-48

ERROR in ../target/frontend/generated-flow-imports.js?babel-target=es5
Module not found: Error: Can't resolve 'src/views/orderedit/order-details.js?babel-target=es5' in 'C:\Users\Johannes\Downloads\npmbakery\target\frontend'
 @ ../target/frontend/generated-flow-imports.js?babel-target=es5 8:0-46

ERROR in ../target/frontend/generated-flow-imports.js?babel-target=es6
Module not found: Error: Can't resolve 'src/views/orderedit/order-details.js?babel-target=es6' in 'C:\Users\Johannes\Downloads\npmbakery\target\frontend'
 @ ../target/frontend/generated-flow-imports.js?babel-target=es6 8:0-46

ERROR in ../target/frontend/generated-flow-imports.js?babel-target=es5
Module not found: Error: Can't resolve 'src/views/orderedit/order-editor.js?babel-target=es5' in 'C:\Users\Johannes\Downloads\npmbakery\target\frontend'
 @ ../target/frontend/generated-flow-imports.js?babel-target=es5 7:0-45

ERROR in ../target/frontend/generated-flow-imports.js?babel-target=es6
Module not found: Error: Can't resolve 'src/views/orderedit/order-editor.js?babel-target=es6' in 'C:\Users\Johannes\Downloads\npmbakery\target\frontend'
 @ ../target/frontend/generated-flow-imports.js?babel-target=es6 7:0-45

ERROR in ../target/frontend/generated-flow-imports.js?babel-target=es5
Module not found: Error: Can't resolve 'src/views/orderedit/order-item-editor.js?babel-target=es5' in 'C:\Users\Johannes\Downloads\npmbakery\target\frontend'
 @ ../target/frontend/generated-flow-imports.js?babel-target=es5 6:0-50

ERROR in ../target/frontend/generated-flow-imports.js?babel-target=es6
Module not found: Error: Can't resolve 'src/views/orderedit/order-item-editor.js?babel-target=es6' in 'C:\Users\Johannes\Downloads\npmbakery\target\frontend'
 @ ../target/frontend/generated-flow-imports.js?babel-target=es6 6:0-50

ERROR in ../target/frontend/generated-flow-imports.js?babel-target=es5
Module not found: Error: Can't resolve 'src/views/storefront/storefront-view.js?babel-target=es5' in 'C:\Users\Johannes\Downloads\npmbakery\target\frontend'
 @ ../target/frontend/generated-flow-imports.js?babel-target=es5 5:0-49

ERROR in ../target/frontend/generated-flow-imports.js?babel-target=es6
Module not found: Error: Can't resolve 'src/views/storefront/storefront-view.js?babel-target=es6' in 'C:\Users\Johannes\Downloads\npmbakery\target\frontend'
 @ ../target/frontend/generated-flow-imports.js?babel-target=es6 5:0-49

ERROR in ../target/frontend/generated-flow-imports.js?babel-target=es5
Module not found: Error: Can't resolve 'styles/shared-styles.js?babel-target=es5' in 'C:\Users\Johannes\Downloads\npmbakery\target\frontend'
 @ ../target/frontend/generated-flow-imports.js?babel-target=es5 4:0-33

ERROR in ../target/frontend/generated-flow-imports.js?babel-target=es6
Module not found: Error: Can't resolve 'styles/shared-styles.js?babel-target=es6' in 'C:\Users\Johannes\Downloads\npmbakery\target\frontend'
 @ ../target/frontend/generated-flow-imports.js?babel-target=es6 4:0-33
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:40 min
[INFO] Finished at: 2019-05-25T11:05:00+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vaadin:flow-maven-plugin:2.0-SNAPSHOT:build-frontend (default) on project npmbakery: Execution default of goal com.vaadin:flow-maven-plugin:2.0-SNAPSHOT:build-frontend failed: Webpack process exited with non-zero exit cod
```e.

**Comment by johannesh2** [comment]
It seems the zip file downloaded does not contain any of the Designer templates

**Comment by manolo** [comment]
remove your node_modules package.json and webpack.config.js and try to run again.

**Comment by bonifacechacha** [comment]
> remove your node_modules package.json and webpack.config.js and try to run again.

The problem is the js templates are not included in the zip file. So even when deleting these it does not resolve the problem

**Comment by alvarezguille** [comment]
Downloaded zip now includes frontend folder with designer templates that were missing.

**Comment by knoobie** [comment]
Not sure if same issue, I downloaded the latest version and got the following error with mvn clean package and mvn clean install:

OS: Ubuntu

[INFO] Updated npm /home/knoobie/projects/vaadin/test/target/frontend/package.json.
[INFO] Running `npm install` ...
npm ERR! addLocal Could not install /home/knoobie/projects/vaadin/test/target/frontend
npm ERR! Linux 4.15.0-50-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2

npm ERR! No version provided in package.json
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/knoobie/projects/vaadin/test/npm-debug.log
[ERROR] >>> Dependency ERROR. Check that all required dependencies are deployed in npm repositories.
[WARNING] Use the './' prefix for resources in JAR files: 'flow-component-renderer.js', please update your component.
[WARNING] Do not use the 'frontend://' protocol in '@JsModule', changing 'frontend://gridConnector.js' to './gridConnector.js', please update your component.
[WARNING] Do not use the 'frontend://' protocol in '@JsModule', changing 'frontend://contextMenuConnector.js' to './contextMenuConnector.js', please update your component.
[WARNING] Do not use the 'frontend://' protocol in '@JsModule', changing 'frontend://datepickerConnector.js' to './datepickerConnector.js', please update your component.
[WARNING] Do not use the 'frontend://' protocol in '@JsModule', changing 'frontend://comboBoxConnector.js' to './comboBoxConnector.js', please update your component.
[INFO] 

  Failed to find the following imports in the `node_modules` tree:
      ➜ @vaadin/vaadin-grid/src/vaadin-grid-column.js
       ➜ @vaadin/vaadin-item/src/vaadin-item.js
       ➜ @vaadin/vaadin-form-layout/src/vaadin-form-item.js
       ➜ @vaadin/vaadin-tabs/src/vaadin-tab.js
       ➜ @vaadin/vaadin-grid/src/vaadin-grid-column-group.js
       ➜ @vaadin/vaadin-icons/vaadin-icons.js
       ➜ @vaadin/vaadin-crud/src/vaadin-crud-edit-column.js
       ➜ @vaadin/vaadin-dialog/src/vaadin-dialog.js
       ➜ @vaadin/vaadin-button/src/vaadin-button.js
       ➜ @vaadin/vaadin-confirm-dialog/src/vaadin-confirm-dialog.js
       ➜ @vaadin/vaadin-app-layout/src/vaadin-app-layout.js
       ➜ @vaadin/vaadin-checkbox/src/vaadin-checkbox.js
       ➜ @vaadin/vaadin-date-picker/src/vaadin-date-picker.js
       ➜ @vaadin/vaadin-charts/vaadin-chart.js
       ➜ @vaadin/vaadin-text-field/src/vaadin-password-field.js
       ➜ @vaadin/vaadin-combo-box/src/vaadin-combo-box.js
       ➜ @vaadin/vaadin-context-menu/src/vaadin-context-menu.js
       ➜ @vaadin/vaadin-tabs/src/vaadin-tabs.js
       ➜ @vaadin/vaadin-text-field/src/vaadin-text-field.js
       ➜ @vaadin/vaadin-list-box/src/vaadin-list-box.js
       ➜ @vaadin/vaadin-notification/src/vaadin-notification.js
       ➜ @vaadin/vaadin-grid/src/vaadin-grid-sorter.js
       ➜ @vaadin/vaadin-crud/src/vaadin-crud.js
       ➜ @vaadin/vaadin-grid/src/vaadin-grid.js
       ➜ @vaadin/vaadin-login/src/vaadin-login-overlay.js
       ➜ @vaadin/vaadin-form-layout/src/vaadin-form-layout.js
       ➜ @vaadin/vaadin-text-field/src/vaadin-email-field.js
  If the build fails, check that npm packages are installed.

[INFO] Updated /home/knoobie/projects/vaadin/test/target/frontend/generated-flow-imports.js
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  26.097 s
[INFO] Finished at: 2019-06-04T15:45:14+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:14.0.0.beta2:build-frontend (default) on project my-starter-project: Execution default of goal com.vaadin:vaadin-maven-plugin:14.0.0.beta2:build-frontend failed: Unable to locate webpack executable by path '/home/knoobie/projects/vaadin/test/node_modules/webpack/bin/webpack.js'. Double check that the plugin is executed correctly -> [Help 1]
[ERROR]

**Comment by alvarezguille** [comment]
> npm ERR! node v8.10.0
npm ERR! npm v3.5.2

NPM version looks outdated, if `npm install` fails then the rest of the build will fail.

If you have a global npm installation, can you try updating npm version? If that doesn't work please create a separate ticket.

Node.js version requirement is already mentioned in [platform release notes](https://github.com/vaadin/platform/releases/tag/14.0.0.beta2) but npm is not mentioned, I'll create a separate ticket for that

**Comment by knoobie** [comment]
Thanks for the heads up about the "old version" - sadly those are the latest versions provided by Ubuntu 18 LTS. If another customer comes around the same issue - here is a instruction how to update the versions within Ubuntu: https://github.com/nodesource/distributions 

Now it's working fine!
